### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by Aaike** [pixelass/more-or-less#4]
Hi, i noticed the [more-or-less](https://www.npmjs.com/package/more-or-less) npm package does not exist yet.
Would you mind publishing this as an npm package as well so we can easily install it ?

**Comment by pixelass** [comment]
It is available via bower. I hope this helps.

**Comment by Aaike** [comment]
I would have liked to install it via `npm install 'more-or-less'` so it can easily be included in my own compilation process , which already uses npm to install gulp and less, so would have been great so simple be able to list more-or-less as a dependency in my package.json.

But nevermind i guess i will use JSPM ;)

**Comment by pixelass** [comment]
that is exactly what bower is for.

```
$ bower install more-or-less --save-dev
```
then on init call it with npm install
```
$ npm install && bower install
```



On Mon, Mar 9, 2015 at 2:32 AM, Aaike Van Roekeghem <
notifications@github.com> wrote:

> I would have liked to install it via npm install 'more-or-less' so it can
> easily be included in my own compilation process , which already uses npm
> to install gulp and less, so would have been great so simple be able to
> list more-or-less as a dependency in my package.json.
>
> But nevermind i guess i will use JSPM ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelass/more-or-less/issues/4#issuecomment-77787989>.
>



-- 
________________________
Gregor Adams
Software developer

Mobile: 0049 172 453 0191
Skype: pixelass
Email: greg@pixelass.com

**Comment by Aaike** [comment]
i know, i would normally install it using JSPM.
but i like to separate things that don't need uploading by installing it though npm.

so npm is for all my dependencies that do not need uploading, or to be used with node only.
and jspm/bower is then for all the front-end assets to be used in the browser.

anyway it's just a matter of preference i suppose.

**Comment by pixelass** [comment]
@Aaike 
More-or-less is now available over npm
[more-or-less](https://www.npmjs.com/package/more-or-less)

Enjoy.

**Comment by Aaike** [comment]
hehe , thanks !
