### ISSUE TITLE
Transition with multiple values not joining correctly

### ISSUE THREAD

**Issue by agelber** [pixelass/more-or-less#6]
Hi there!

I am trying to add multiple transitions to an element but running into a problem where the values aren't joined using a space instead of a comma (on version 1.5.1). 

__So for example:__
```
.transition(color 0.5s, transform 1s);
```
__outputs:__
```
transition: color 0.5s transform 1s;
```
(notice the missing comma between the two)

Let me know if I am misunderstanding something or whether this is an bug.
I'm new to less, but will try to fix this myself and open up a PR unless someone beats me to it.

Many many thanks! :beers:

**Comment by pixelass** [comment]
Thx for reporting. I will look into this later. I remember a bug in that section and think it will not work with this syntax. But just to make sure I will check it in the evening.

**Comment by agelber** [comment]
Sure thing. Very much appreciated! :bouquet:

**Comment by pixelass** [comment]
@agelber  Please look at this test https://github.com/pixelass/more-or-less/blob/master/test/test.less#L55

try: ([...],[...];) <--- semicolon inside brackets

```
.transition(color 0.5s, transform 1s;);
```

**Comment by agelber** [comment]
Ahhhh, I see. Yeah, that works! :100: 
Thanks again!

**Comment by agelber** [comment]
Would it be ok if I open a PR reflecting this in the transitions README?

**Comment by pixelass** [comment]
sure thing.. the readme has a wrong example anyways
